redpanda-data/documentation

- docs/console/reference/config.mdx
Duplicate key causes the example to throw duplicate key error.
> Update doc to remove duplicate key

- docs/install-upgrade/rolling-upgrade.mdx
- versioned_docs/version-22.1/cluster-administration/node-management.mdx
Changing `rpk maintenance mode disable` to `rpk cluster maintenance disable`
Related Docs:
https://docs.redpanda.com/docs/reference/rpk/rpk-cluster/rpk-cluster-maintenance-disable/
This comes from a thread in the community channel: https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1666099640386339
> Bug: rpk maintenance to rpk cluster maintenance

- docs/reference/redpanda-operator/index.mdx
- docs/reference/redpanda-operator/kubernetes-sasl.mdx
- docs/reference/redpanda-operator/tls-kubernetes.mdx
- docs/security/index.mdx
- docs/security/sasl-kubernetes.mdx
- sidebars.js
Fixes #615 
Preview:
- https://deploy-preview-706--redpanda-documentation.netlify.app/docs/security/
- https://deploy-preview-706--redpanda-documentation.netlify.app/docs/security/sasl-kubernetes/
- https://deploy-preview-706--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/
- https://deploy-preview-706--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/kubernetes-sasl/
- https://deploy-preview-706--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/tls-kubernetes/
> add documentation for configuring SASL with the helm chart

- docs/platform/deployment/production-deployment.mdx
This updates the `rpk config...` commands to use the new version of the commands.
> Update deprecated rpk commands in prod deployment doc

- docs/platform/data-management/data-migration.mdx
Update to 3.3.1
Avoid prefixes on topic names since this is for migration
> Avoid topic name prefixes

- docs/platform/cluster-administration/node-management.mdx
- docs/platform/install-upgrade/rolling-upgrade.mdx
In "Node Maintenance Mode", added note that node cannot be decommissioned while in maintenance mode.
In "Rolling Upgrade", expanded on instructions to take node out of maintenance mode if cluster is unhealthy. Users might want to decommission the unhealthy node, but won't be able to if it's still in maintenance mode.
Resolves issue #522 .
> docs:#522 maintenance mode

- docs/platform/reference/rpk/rpk-redpanda/rpk-redpanda-start.mdx
This help text was missing in rpk when v22.3 docs were created.
See: https://github.com/redpanda-data/redpanda/pull/7413
> rpk: add fetch_reads_debounce_timeouts to start

- docs/platform/quickstart/kubernetes-qs-dev.mdx
- expand prerequisites to include `aws` and `eksctl` CLIs
- add info on required IAM permissions
- add command to update kubeconfig to point to new cluster
> Minor improvements to AWS EKS quickstart

- docs/platform/quickstart/kubernetes-qs-dev.mdx
This PR requires the following helm chart PR to be merged first: https://github.com/redpanda-data/helm-charts/pull/220
This details how to make use of new features in the helm chart to customize external access. The process would be slightly different if DNS is a factor, and this is mentioned as other paths (paths 2 and 3) in this doc. These paths are not covered though since they entirely depend on how the user would need to update/manage DNS. They could be using Route53, hosts file, a custom DNS service, etc.
> Adds details on how to customize external access

- docs/platform/reference/redpanda-operator/kubernetes-qs-cloud.mdx
- docs/platform/reference/redpanda-operator/kubernetes-qs-local-access.mdx
- docs/platform/reference/redpanda-operator/kubernetes-qs-minikube.mdx
- docs/platform/reference/redpanda-operator/kubernetes-sasl.mdx
- docs/platform/reference/redpanda-operator/tls-kubernetes.mdx
- src/theme/Admonition/index.js
- src/theme/Admonition/styles.module.css
Resolves #703 
Preview: 
https://deploy-preview-909--redpanda-documentation.netlify.app/docs/platform/reference/redpanda-operator/kubernetes-qs-cloud
https://deploy-preview-909--redpanda-documentation.netlify.app/docs/platform/reference/redpanda-operator/kubernetes-qs-local-access
https://deploy-preview-909--redpanda-documentation.netlify.app/docs/platform/reference/redpanda-operator/kubernetes-qs-minikube
https://deploy-preview-909--redpanda-documentation.netlify.app/docs/platform/reference/redpanda-operator/kubernetes-sasl
https://deploy-preview-909--redpanda-documentation.netlify.app/docs/platform/reference/redpanda-operator/tls-kubernetes
Also every other place that uses the admonition INFO.
> docs: change kubernetes admonitions to red

- docs/platform/deployment/production-deployment.mdx
This PR attempts to improve the production deployment page instructions so there is one "Configure and start nodes" section. Some sentences and comments are also modified to clarify these instructions need to be ran on each node in the cluster. My previous comments in slack around why this PR exists:
> I think the confusing part for me is separating seed servers into one section, and all other nodes into another (combined with the fact that the steps are identical for each). I would expect that with 22.3 we would just assume any/all nodes are listed as seed servers, so all nodes are seed servers and we don't have to distinguish between them in this way. We could just say "Configure and start nodes" and then remove the next section "Configure and start other nodes"
> Merge node sections on production deployment page

- versioned_docs/version-21.11/data-management/data-migration.mdx
Resolves #672 
Preview: 
https://deploy-preview-917--redpanda-documentation.netlify.app/docs/21.11/data-management/data-migration/#run-mirrormaker-to-start-replication
> docs: remove note for consumer offset in v22.11

- docs/platform/console/reference/config.mdx
Adds the currently undocumented configuration properties which have been added in the latest minor or patch release
> console: Add recently added config properties

- docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
I added two guides which are supposed to help troubleshooting when using the generic OIDC provider. They are not very straightforward, but this is currently the best what we can do until we spend more time on improving the behaviour.
> console: Add guide for troubleshooting oidc

- docs/platform/console/reference/docker-compose.mdx
This PR updates the docker compose reference file to the latest recommended versions and configurations.
PS: As suggested via Slack I'd be interested in moving this docker compose to a central place, so that there's only a single Docker compose for all Redpanda platform.
> console: Update docker compose sample

- docs/platform/data-management/data-migration.mdx
- docs/platform/deployment/production-deployment.mdx
The original command fails with 
```
$ rpk topic alter-config test3 --set replication.factor 3
unable to parse --set: unable to find key=value pair in "replication.factor"
```
This should be 
```
$ rpk topic alter-config test3 --set replication.factor=3
TOPIC  STATUS
test3  OK
```
> docs: Correct changing replication.factor value command

- docs/platform/reference/tunable-properties.mdx
Fixes #1020 .
Review deadline: Fri Jan 13
Added 'Restart required' for tunable properties, as specified by `needs_restart` meta data in https://github.com/redpanda-data/redpanda/blob/dev/src/v/config/configuration.cc (where unspecified/default is `needs_restart::yes`).
Preview: https://deploy-preview-1021--redpanda-documentation.netlify.app/docs/platform/reference/tunable-properties/
@jcsp @vuldin need an SME review, at minimum a spot-check of some properties.
> docs #1020 added 'Restart required' for tunable properties

- docs/platform/deploy/kubernetes-tune-workers.mdx
The following site display both option https://docs.redpanda.com/docs/platform/deploy/kubernetes-tune-workers/#install-redpanda
The tabs was defined, but we missed the include.
> Add missing import for tab and tabs library

- docs/platform/security/kubernetes-tls.mdx
- versioned_docs/version-22.2/platform/security/kubernetes-tls.mdx
The modal in Artifact hub is more user friendly and should be more stable.
> Change Github wrong link to helm Artifact hub

- docs/manage/security/console/authentication.mdx
- docs/manage/security/console/generic-oidc.mdx
- docs/manage/security/console/github.mdx
- docs/manage/security/console/google.mdx
- docs/manage/security/console/okta.mdx
- docs/reference/console/config.mdx
This PR aims to improve the documentation around the `login.jwtSecret` configuration in Console which is important from a security standpoint. The goal is to inform the user about it's importance as well as having a single consistent documentation for the property.
> console: Provide more precise docs for jwtSecret

- src/theme/DocItem/Layout/index.js
- src/theme/DocItem/Layout/styles.module.css
This PR allows us to submit feedback forms to Netlify.
- Fixed an issue with empty fields in Netlify submissions by saving each value to the state.
- Moved only essential browser-only content inside `<BrowserOnly>`. If forms are inside this component, Netlify can't detect them. The only part that needs to be in `<BrowserOnly>` is the link that accesses the `window` object.
- Removed the condition that doesn't render the form. We need Netlify to see the form when the site it built, but this condition was stopping the form from being rendered.
```
if (!props.show) {
return null;
}
```
- Renamed the hidden input name to `form-name`. See https://docs.netlify.com/forms/setup/#work-with-javascript-rendered-forms
- Fixed some logic to get the success message to be displayed and to stop form …
> Fix Netlify form submissions

- docs/deploy/deployment-option/self-hosted/manual/sizing.mdx
- docs/manage/cluster-maintenance/disk-utilization.mdx
- docs/reference/tunable-properties.mdx
Fixes: 
- #1016 
Preview: 
- https://deploy-preview-1082--redpanda-documentation.netlify.app/docs/reference/tunable-properties/#log_segment_size
> update log_segment_size default for v23.1

- docs/manage/security/iam-roles.mdx
- docs/manage/tiered-storage.mdx
- versioned_docs/version-22.2/security/iam-roles.mdx
This PR updates the following pages:
https://docs.redpanda.com/docs/platform/security/iam-roles/
https://docs.redpanda.com/docs/22.2/platform/security/iam-roles/
https://docs.redpanda.com/docs/platform/data-management/tiered-storage/
What are changed?
* Remove unnecessary action, like `s3-object-lambda`
* Add minimum (least) privilege required for Tiered Storage
> Docs: Revise IAM policies with more information

- docs/manage/cluster-maintenance/configure-availability.mdx
- docs/manage/cluster-maintenance/index.mdx
- docs/manage/cluster-maintenance/shared/_intro-configure-availability.mdx
- docs/reference/cluster-properties.mdx
- docs/reference/node-properties.mdx
- sidebars.js
Fixes for 23.1:
- #1114 
Previews:
- [New Node property](https://deploy-preview-1131--redpanda-documentation.netlify.app/docs/reference/node-properties/#crash_loop_limit)
- [New section in Configure Availability topic](https://deploy-preview-1131--redpanda-documentation.netlify.app/docs/manage/cluster-maintenance/configure-availability/#prevent-crash-loops) (note: cherry-picked Configure Availability from dev)
Review deadline: Wed Feb 1
> Document crash_loop_limit node configuration for 23.1

- docusaurus.config.js
- src/theme/DocVersionBanner/index.js
Updated unreleased (Beta) version banner with version number (23.1) and link to announcement in Redpanda Community.
Preview:
- https://deploy-preview-1184--redpanda-documentation.netlify.app/docs/beta/home/
> Beta banner

- versioned_docs/version-22.2/cluster-administration/monitoring.mdx
- versioned_docs/version-22.2/reference/internal-metrics.mdx
Fixes:
- #967 
Previews:
- 22.2: updated [public metrics](https://deploy-preview-1145--redpanda-documentation.netlify.app/docs/22.2/cluster-administration/monitoring/) and [internal metrics](https://deploy-preview-1145--redpanda-documentation.netlify.app/docs/22.2/reference/internal-metrics/) pages with note
- (22.3: previously resolved by #1059)
> Clarify public_metrics and metrics export different metrics for 22.2

- docs/reference/cluster-properties.mdx
Fix #1172 
Is this the right place to document these? I notice that `kafka_mtls_principal_mapping_rules` and `kafka_enable_authorization` are also missing from here.
Signed-off-by: Ben Pope <ben@redpanda.com>
> cluster_config: Kerberos support

- docs/reference/tunable-properties.mdx
Review deadline: Fri Feb 10
Fixes:
- #1076 
Preview: 
- [New tunable properties](https://deploy-preview-1190--redpanda-documentation.netlify.app/docs/beta/reference/tunable-properties/#group_offset_retention_check_ms)
> Document group offset retention properties for v23.1

- docs/deploy/deployment-option/cloud/vpc-peering.mdx
- versioned_docs/version-22.2/cloud/vpc-peering.mdx
- versioned_docs/version-22.3/deploy/deployment-option/cloud/vpc-peering.mdx
VPC peering connection can only be created between customer's and Redpanda VPC networks residing in the same region. Add this information to the prerequisities section of the VPC peering doc.
Ref: https://github.com/redpanda-data/cloudv2/issues/4396
> vpc-peering: add matching region requirements

- src/css/custom.css
Fixes:
- #1210 
The specific goal of this PR is to prevent code blocks with long, unbroken strings from forcing the right-nav TOC off the visible screen.
Previews of pages that previously had code blocks so wide that they pushed the right-nav TOC to the bottom:
- https://deploy-preview-1224--redpanda-documentation.netlify.app/docs/manage/security/encryption/
- https://deploy-preview-1224--redpanda-documentation.netlify.app/docs/develop/http-proxy/
> Limit width of code-blocks to prevent wraparound of TOC

- docs/deploy/deployment-option/self-hosted/manual/production/production-deployment.mdx
- versioned_docs/version-22.3/deploy/deployment-option/self-hosted/manual/production/production-deployment.mdx
Fixes:
- #1118 
Preview:
- Updated both [23.1's Deploy for production page](https://deploy-preview-1244--redpanda-documentation.netlify.app/docs/beta/deploy/deployment-option/self-hosted/manual/production/production-deployment/) and [22.3's page](https://deploy-preview-1244--redpanda-documentation.netlify.app/docs/deploy/deployment-option/self-hosted/manual/production/production-deployment/), moved tabbed content into separate headings. 
Future task:
- Fix root cause in Docusaurus of linking from TOC to disabled tabs
> Workaround fix for TOC of Deploy for production page 

- docs/manage/schema-registry.mdx
- docs/reference/cluster-properties.mdx
- docs/reference/tunable-properties.mdx
Review deadline: Tue Feb 14
Fixes:
- #1072 
- #1188 
Previews:
- Added rest of the [tunable properties](https://deploy-preview-1203--redpanda-documentation.netlify.app/docs/reference/tunable-properties/) and [cluster properties](https://deploy-preview-1203--redpanda-documentation.netlify.app/docs/reference/cluster-properties/) that are new in 23.1 or were previously supported but undocumented.
> Document missing tunable and cluster properties in 23.1

- docs/reference/cluster-properties.mdx
Fixed the description of the kafka_quota_balancer_min_shard_throughput_ratio property: https://deploy-preview-1258--redpanda-documentation.netlify.app/docs/beta/reference/cluster-properties/#kafka_quota_balancer_min_shard_throughput_ratio
> fix kafka_quota_balancer_min_shard_throughput_ratio description

- docs/reference/docker-compose.mdx
Fix this error using the last tag in the docker hub (1.0.0-dev-bc9a905)
Error response from daemon: manifest for docker.redpanda.com/redpandadata/connectors:1.0.0-dev-dff1c57 not found: manifest unknown: manifest unknown
> docs: fix connectors image tag

- versioned_docs/version-22.3/reference/docker-compose.mdx
The version `redpandadata/connectors:1.0.0-dev-dff1c57` used in the doc does not exist so the container from the example does not work.
> Use `latest` connectors image version in owl-shop example

- docs/reference/cluster-properties.mdx
I didn't realize `partition_autobalancing_mode` set to `continuous` would include all the benefits of `node_add`. This small change make this associated between these two values more clear.
> `continuous` autobalancing mode includes benefits of `node_add` mode

- docs/develop/config-topics.mdx
- sidebars.js
Explains how to configure topics from the `rpk` command line. Offers guidance for determining the number of partitions to use, and a recommendation for the number of replicas. Also covers the `rpk topic delete` command and the `rpk topic describe` command.
Fixes #887 
Review deadline: Thursday, March 23, 2023.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204218351694977
> docs:#887 add "Configuring Topics"

- docusaurus.config.js
- src/theme/DocItem/Layout/index.js
Following [Mouseflow's Custom Variables guide](https://help.mouseflow.com/en/articles/4312070-custom-variables), added Mouseflow variables `positive-feedback` and `negative-feedback` that are set `true` when the thumbs-up and thumbs-down buttons are clicked, respectively.
Can now filter for and observe Mouseflow recordings where positive or negative feedback are clicked.
> Add mouseflow custom variables to track positive/negative feedback

- docs/manage/security/console/authentication.mdx
- docs/manage/security/console/azure-ad.mdx
- docs/manage/security/console/generic-oidc.mdx
- docs/manage/security/console/github.mdx
- docs/manage/security/console/google.mdx
- docs/manage/security/console/index.mdx
- docs/manage/security/console/keycloak.mdx
- docs/manage/security/console/okta.mdx
- sidebars.js
This PR adds Azure AD & Keycloak documentation for the upcoming Console release. It's still missing content that describes how to create the OIDC application in the respective identity provider. I asked Anne to help here and I'll meet with her next week to show how it's done. 
Resolves #1481
> console: Add Azure & Keycloak docs

- docs/manage/security/iam-roles.mdx
IMDSv2 is now default in new instances, which breaks tiered storage. This update adds an additional step to verify IMDSv2 is optional on EC2 instances.
> Add IMDS details

- docs/develop/http-proxy.mdx
Adds curl, python, and JavaScript examples for providing SCRAM username and password. Also picked up some whitespace changes. 😬
> Add examples for using Basic Auth with the HTTP Proxy.

- docs/deploy/deployment-option/cloud/vpc-peering.mdx
When creating a redpanda cloud dedicated cluster with a private network, the `CIDR` field has a pop-up help text:
> NOTE: The range must not overlap with the IP range of the VPC peering network.
And according to AWS [docs](https://docs.aws.amazon.com/vpc/latest/peering/vpc-peering-basics.html) on VPC peering limitations:
> You cannot create a VPC peering connection between VPCs that have matching or overlapping IPv4 CIDR blocks.
This PR adds additional text to the docs to identify this point in the `Prerequisites` section.
> vpc-peering: add non-overlapping cidr block prerequisites

- docs/reference/docker-compose.mdx
Environment variables seem busted. Also adds a healthcheck for Redpanda as owlshop will fail fast and not retry to connect if the broker interface isn't ready.
> Switch owl-shop example to use yaml config.

- docs/reference/redpanda-operator/kubernetes-external-connect.mdx
- docs/reference/redpanda-operator/kubernetes-qs-cloud.mdx
- docs/reference/redpanda-operator/kubernetes-qs-local-access.mdx
- docs/reference/redpanda-operator/kubernetes-qs-minikube.mdx
- versioned_docs/version-21.11/quickstart/kubernetes-qs-minikube.mdx
- versioned_docs/version-22.1/deployment/kubernetes-external-connect.mdx
- versioned_docs/version-22.1/quickstart/kubernetes-qs-cloud.mdx
- versioned_docs/version-22.1/quickstart/kubernetes-qs-local-access.mdx
- versioned_docs/version-22.1/quickstart/kubernetes-qs-minikube.mdx
- versioned_docs/version-22.2/reference/redpanda-operator/kubernetes-external-connect.mdx
- versioned_docs/version-22.2/reference/redpanda-operator/kubernetes-qs-cloud.mdx
- versioned_docs/version-22.2/reference/redpanda-operator/kubernetes-qs-local-access.mdx
- versioned_docs/version-22.2/reference/redpanda-operator/kubernetes-qs-minikube.mdx
- versioned_docs/version-22.3/reference/redpanda-operator/kubernetes-external-connect.mdx
- versioned_docs/version-22.3/reference/redpanda-operator/kubernetes-qs-cloud.mdx
- versioned_docs/version-22.3/reference/redpanda-operator/kubernetes-qs-local-access.mdx
- versioned_docs/version-22.3/reference/redpanda-operator/kubernetes-qs-minikube.mdx
- versioned_docs/version-23.2/reference/redpanda-operator/kubernetes-external-connect.mdx
- versioned_docs/version-23.2/reference/redpanda-operator/kubernetes-qs-cloud.mdx
- versioned_docs/version-23.2/reference/redpanda-operator/kubernetes-qs-local-access.mdx
Update `cert-manager` used in quickstart guides from `v1.7.0` to `v1.12.2.` The current version is already E[OL since July 2022 and only supports K8s versions up to `1.23`, so it does not work with newer clusters.](https://cert-manager.io/docs/installation/supported-releases/)
> docs: update cert-manager used in quickstart guides to v1.12.2

- docs/upgrade/migrate/kubernetes/helm-to-operator.mdx
@mattschumpert pointed out to me that this read as if he was replacing his Redpanda cluster instead of adopting it into the operator.
Soften the wording to make it clearer.
> clarify adopting not deploying

- docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_deploy-redpanda.mdx
The helm install command tends to timeout even with only 3 brokers (which is default). The default timeout is 5m, which is right around how long the install and or rolling restart takes.
> Add timeout to helm install

- docs/manage/data-migration.mdx
Redpanda now has a max message size unlike in previous versions.
> Remove max message size comment
