docs/cluster-administration/configuration.mdx, docs/data-management/data-migration.mdx, docs/deployment/production-deployment.mdx, docs/reference/rpk/rpk-topic/rpk-topic-alter-config.mdx
resolves #601 
preview: 
https://deploy-preview-739--redpanda-documentation.netlify.app/docs/data-management/data-migration/#change-topic-replication-factor
https://deploy-preview-739--redpanda-documentation.netlify.app/docs/deployment/production-deployment/#verify-the-installation
https://deploy-preview-739--redpanda-documentation.netlify.app/docs/cluster-administration/configuration/
https://deploy-preview-739--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-topic/rpk-topic-alter-config/
=> Docs: #601change topic replication factor

docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
Follow up from a support case with a prospect
=> console: Document redirect URI and clarify binding

docs/home/platform/platform.js, versioned_docs/version-21.11/home/HomepageFeatures.js, versioned_docs/version-22.1/home/HomepageFeatures.js
=> docs: fix homepage tile

docs/platform/reference/redpanda-operator/crd.mdx, sidebars.js
Resolves #400 
https://deploy-preview-824--redpanda-documentation.netlify.app/docs/platform/reference/redpanda-operator/crd/
=> docs: add crd page for consistency

docs/platform/reference/rpk/rpk-cloud/rpk-cloud-byoc-install.mdx, docs/platform/reference/rpk/rpk-cloud/rpk-cloud-byoc-uninstall.mdx, docs/platform/reference/rpk/rpk-cloud/rpk-cloud-byoc.mdx, docs/platform/reference/rpk/rpk-cloud/rpk-cloud-login.mdx, docs/platform/reference/rpk/rpk-cloud/rpk-cloud-logout.mdx, docs/platform/reference/rpk/rpk-cloud/rpk-cloud.mdx, docs/platform/reference/rpk/rpk-iotune.mdx, docs/platform/reference/rpk/rpk-plugin/rpk-plugin-install.mdx, docs/platform/reference/rpk/rpk-plugin/rpk-plugin-list.mdx, docs/platform/reference/rpk/rpk-plugin/rpk-plugin-uninstall.mdx, docs/platform/reference/rpk/rpk-plugin/rpk-plugin.mdx, docs/platform/reference/rpk/rpk-redpanda/rpk-redpanda-config-bootstrap.mdx, docs/platform/reference/rpk/rpk-redpanda/rpk-redpanda-start.mdx, docs/platform/reference/rpk/rpk-topic/rpk-topic-consume.mdx, docs/platform/reference/rpk/rpk-topic/rpk-topic-produce.mdx, docs/platform/reference/rpk/rpk-topic/rpk-topic.mdx, sidebars.js, tools/rpk-commands.mdx, versioned_docs/version-21.11/reference/rpk-commands.mdx, versioned_docs/version-22.1/reference/rpk-commands.mdx
Preview: 
https://deploy-preview-784--redpanda-documentation.netlify.app/
https://deploy-preview-784--redpanda-documentation.netlify.app/docs/platform/reference/rpk/rpk-cloud/rpk-cloud
https://deploy-preview-784--redpanda-documentation.netlify.app/docs/platform/reference/rpk/rpk-cloud/rpk-cloud-login
https://deploy-preview-784--redpanda-documentation.netlify.app/docs/platform/reference/rpk/rpk-cloud/rpk-cloud-logout
https://deploy-preview-784--redpanda-documentation.netlify.app/docs/platform/reference/rpk/rpk-plugin/rpk-plugin
https://deploy-preview-784--redpanda-documentation.netlify.app/docs/platform/reference/rpk/rpk-redpanda/rpk-redpanda-config-bootstrap
https://deploy-preview-784--redpanda-documentation.netlify.app/docs/platform/reference/rpk/rpk-topic/rpk-topic
=> updates rpk to 22.3

src/css/custom.css
=> engine: apply new font

docs/platform/reference/node-properties.mdx, versioned_docs/version-22.1/reference/node-properties.mdx, versioned_docs/version-22.2/platform/reference/node-properties.mdx
Resolves #652 
Preview: 
https://deploy-preview-858--redpanda-documentation.netlify.app/docs/platform/reference/node-properties/
https://deploy-preview-858--redpanda-documentation.netlify.app/docs/22.2/platform/reference/node-properties/
https://deploy-preview-858--redpanda-documentation.netlify.app/docs/22.1/reference/node-properties/
=> docs: change node properties description and add note

docs/platform/install-upgrade/version-upgrade.mdx, versioned_docs/version-21.11/cluster-administration/version-upgrade.mdx, versioned_docs/version-22.1/cluster-administration/version-upgrade.mdx, versioned_docs/version-22.2/platform/install-upgrade/version-upgrade.mdx
Resolves #552 
Preview: 
https://deploy-preview-859--redpanda-documentation.netlify.app/docs/platform/install-upgrade/version-upgrade/#upgrading-your-version
https://deploy-preview-859--redpanda-documentation.netlify.app/docs/22.2/platform/install-upgrade/version-upgrade/#upgrading-your-version
https://deploy-preview-859--redpanda-documentation.netlify.app/docs/22.1/cluster-administration/version-upgrade/#upgrading-your-version
https://deploy-preview-859--redpanda-documentation.netlify.app/docs/21.11/cluster-administration/version-upgrade/#upgrading-your-version
=> docs: add note about support regarding version upgrade

docs/platform/reference/tunable-properties.mdx
Resolves #598 
Preview: 
https://deploy-preview-892--redpanda-documentation.netlify.app/docs/platform/reference/tunable-properties/
=> docs: fix tunable properties default value

docs/platform/quickstart/console-installation.mdx
=> console: Improve console quickstart docs

docs/platform/deployment/production-deployment.mdx
The [previous PR](https://github.com/redpanda-data/documentation/pull/832) for this branch was accidentally merged then reverted.
=> Merge prod deploy node sections

docs/platform/console/features/schema-registry.mdx, docs/platform/data-management/index.mdx, docs/platform/data-management/schema-registry.mdx, docs/platform/deployment/production-deployment.mdx, docs/platform/reference/index.mdx, docs/platform/reference/node-configuration-sample.mdx, docs/platform/reference/redpanda-operator/kubernetes-connectivity.mdx, docs/platform/reference/redpanda-operator/kubernetes-mtls.mdx, docs/platform/reference/redpanda-operator/tls-kubernetes.mdx, docs/platform/reference/schema-registry-api.mdx, docs/platform/security/encryption.mdx, docusaurus.config.js, sidebars.js
Resolves #842 
First sub-issue of Schema Registry epic #52
=> docs: #842: create new Schema Registry topic with blog post content and API reference link

docs/platform/development/configure-producers.mdx, docs/platform/development/index.mdx, sidebars.js
Resolves #943 
New topic: Configuring Producers
To view HTML output: https://deploy-preview-977--redpanda-documentation.netlify.app/docs/platform/development/configure-producers/
=> Configuring Producers doc

docs/cloud/create-byoc-cluster-gcp.mdx, sidebars.js
New doc for creating a BYOC cluster in GCP. This PR addresses issue #988
=> Create BYOC cluster GCP

docs/platform/deploy/kubernetes-best-practices.mdx
The PVC and POD can be created and retrospectively user could create PV and bind it to PVC.
=> Reword dynamic provisioner absense

docs/get-started/quick-start/kubernetes-qs-dev.mdx
=> Correct missing line continuation

docs/deploy/deployment-option/self-hosted/manual/production/production-deployment.mdx, docs/reference/node-properties.mdx
Fixes #1049 .
Review deadline: Fri Jan 20.
=> docs: fix default and description for empty_seed_starts_cluster property

src/theme/DocSidebar/Mobile/index.js
Fixes:
- #1074 
Preview:
- View on Mobile (or use [Google Chrome's Developer Tools](https://developer.chrome.com/docs/devtools/device-mode/)):  https://deploy-preview-1075--redpanda-documentation.netlify.app/
=> docs #1074: added SearchBar for Mobile

docs/manage/cluster-maintenance/configure-availability.mdx, docs/manage/cluster-maintenance/index.mdx, docs/manage/cluster-maintenance/shared/_intro-configure-availability.mdx, docs/reference/cluster-properties.mdx, sidebars.js
Fixes:
- #354 
Preview:
- New topic [Configure Availability](https://deploy-preview-1109--redpanda-documentation.netlify.app/docs/manage/cluster-maintenance/configure-availability/)
**Review deadline**: Fri Jan 27
=> Document client connection quotas

docs/manage/monitoring.mdx, docs/reference/cluster-properties.mdx, docs/reference/index.mdx, docs/reference/internal-metrics-reference.mdx, docs/reference/internal-metrics.mdx, docs/reference/monitor-metrics.mdx, docs/reference/public-metrics-reference.mdx, docs/shared/_metrics-usage-tip.mdx, sidebars.js, versioned_docs/version-22.2/cluster-administration/monitoring.mdx
Fixes: 
- #140 
- #1046 
- #1014 
- #702 
- #1087 
- #1099 
Previews:
- Updated topic [Monitor Redpanda](https://deploy-preview-1059--redpanda-documentation.netlify.app/docs/manage/monitoring/)
- New/reorganized references for [Public and Internal Metrics](https://deploy-preview-1059--redpanda-documentation.netlify.app/docs/reference/monitor-metrics/)
**Review deadline: Thu Jan 26**
=> Information on what to monitor for Redpanda

src/theme/DocItem/Layout/index.js, src/theme/DocItem/Layout/styles.module.css
=> engine: captures more data  from feedbackform

docusaurus.config.js
=> engine: add beta path

src/theme/DocVersionBanner/index.js
Change text in beta banner to "This is in-progress documentation ..."
=> update beta banner to in-progress documentation

docs/manage/cluster-maintenance/index.mdx, docs/manage/cluster-maintenance/manage-throughput.mdx, docs/manage/cluster-maintenance/shared/_intro-manage-throughput.mdx, docs/reference/cluster-properties.mdx, docs/reference/node-properties.mdx, docs/reference/tunable-properties.mdx, sidebars.js
Merge (cherry-picked) the approved PR #1140 from branch `23.1` to `dev`
=> Document cluster wide rate limits for 23.1 (#1140)

docs/reference/tunable-properties.mdx
Review deadline: Fri Feb 10
Fixes:
- #1077 
Preview:
- New [node_isolation_heartbeat_timeout tunable property](https://deploy-preview-1186--redpanda-documentation.netlify.app/docs/beta/reference/tunable-properties/#node_isolation_heartbeat_timeout)
=> Add node_isolation_heartbeat_timeout tunable property

versioned_docs/version-22.3/deploy/deployment-option/self-hosted/manual/sizing.mdx
=> port PR #1216 to v22.3

docs/deploy/deployment-option/self-hosted/kubernetes/eks-guide.mdx, docs/deploy/deployment-option/self-hosted/kubernetes/get-started-dev.mdx, docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-cluster-requirements.mdx, docs/deploy/deployment-option/self-hosted/kubernetes/shared/_default-components.mdx, docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_external-access-intro.mdx, docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_next-steps.mdx, docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_operator-note.mdx, docs/get-started/quick-start.mdx, docs/manage/kubernetes/networking/configure-listeners.mdx, docs/manage/kubernetes/networking/networking-and-connectivity.mdx, docs/manage/kubernetes/shared/_listener-nodeports.mdx, versioned_docs/version-22.3/deploy/deployment-option/self-hosted/kubernetes/get-started-dev.mdx, versioned_docs/version-22.3/deploy/deployment-option/self-hosted/kubernetes/kubernetes-cluster-requirements.mdx, versioned_docs/version-22.3/deploy/deployment-option/self-hosted/kubernetes/shared/_default-components.mdx, versioned_docs/version-22.3/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_operator-note.mdx, versioned_docs/version-22.3/get-started/quick-start.mdx, versioned_docs/version-22.3/manage/kubernetes/networking/configure-listeners.mdx, versioned_docs/version-22.3/manage/kubernetes/networking/networking-and-connectivity.mdx, versioned_docs/version-22.3/manage/kubernetes/shared/_listener-nodeports.mdx
Suggestions from Alex and general improvements/fixes.
=> docs: Improve Kubernetes guides with more details

docs/develop/kafka-clients.mdx
=> Clarify unsupport AK features

docs/reference/console/config.mdx
Respective PR: https://github.com/redpanda-data/console/pull/664
=> console: Document startup config block

versioned_docs/version-23.2/manage/monitoring.mdx, versioned_docs/version-23.2/reference/rpk/rpk-generate/rpk-generate-grafana-dashboard.mdx
=> update rpk generate grafana dashboards usage for 23.2

docs/reference/tunable-properties.mdx, versioned_docs/version-22.3/reference/tunable-properties.mdx, versioned_docs/version-23.2/reference/tunable-properties.mdx
=> Improve description for members_backend_retry_ms

docs/manage/cluster-maintenance/decommission-brokers.mdx, docs/manage/kubernetes/decommission-brokers.mdx
This PR updates the decommission pages to include details on how to verify whether a decommission is possible, as well as lists some other considerations. The decommission steps are also expanded to include how to verify cluster health after each decommission step is complete. Details on monitoring the cluster during and after decommission are also given.
https://deploy-preview-1575--redpanda-documentation.netlify.app/docs/manage/cluster-maintenance/decommission-brokers/
https://deploy-preview-1575--redpanda-documentation.netlify.app/docs/manage/kubernetes/decommission-brokers/
=> Update decommission steps

docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-brokers-decommission-status.mdx, docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-brokers-decommission.mdx, docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-brokers-list.mdx, docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-brokers-recommission.mdx, docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-brokers.mdx
These were missing and now are being added in
redpanda/#11650: https://github.com/redpanda-data/redpanda/pull/11650
=> rpk: adding sasl flags to rpk redpanda admin commands

.github/CODEOWNERS
Needed so that PRs approved by Paulo can be merged
=> Add @deflaimun as code owner

docusaurus.config.js, src/theme/DocVersionBanner/index.js
Resolves #1356 for docusaurus
Preview: 
https://deploy-preview-1745--redpanda-documentation.netlify.app/docs/21.11/home/
https://deploy-preview-1745--redpanda-documentation.netlify.app/docs/22.1/home/
=> engine: add Eol version banner

docs/reference/api-reference.mdx
Add Admin API to [23.2 API reference](https://deploy-preview-1780--redpanda-documentation.netlify.app/docs/reference/api-reference/)
=> Add Admin API reference page to 23.2 doc

docs/reference/cluster-properties.mdx
This PR re adds the cluster properties introduced in #1542
=> docs: re add cluster properties

docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_start-streaming.mdx
helm chart default SASL mechanism is SCRAM-SHA-512
=> Update mechanism from 256 to 512

docs/manage/cluster-maintenance/disk-utilization.mdx
=> Add Configure Offset Retention

docs/reference/node-properties.mdx, versioned_docs/version-22.1/reference/node-properties.mdx, versioned_docs/version-22.2/reference/node-properties.mdx, versioned_docs/version-22.3/reference/node-properties.mdx, versioned_docs/version-23.1/reference/node-properties.mdx
=> Add restart-required admonition to node properties reference

docs/deploy/deployment-option/cloud/cloud-overview.mdx
=> Redpanda Cloud-platform compatibility

docs/develop/http-proxy.mdx
=> Use base-uri variable for curl requests

docs/labs/data-transform/index.mdx
Partially addresses the feedback that I gave in #1813
=> Update Data Transform Tutorial using new assets

docs/reference/cluster-properties.mdx, versioned_docs/version-22.3/reference/cluster-properties.mdx, versioned_docs/version-23.1/reference/cluster-properties.mdx
=> Improve description of raft_learner_recovery_rate
